// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: history.proto

package coins_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoryService_HistoryUser_FullMethodName       = "/coins_service.HistoryService/HistoryUser"
	HistoryService_HistoryUserAll_FullMethodName    = "/coins_service.HistoryService/HistoryUserAll"
	HistoryService_HistoryMessage_FullMethodName    = "/coins_service.HistoryService/HistoryMessage"
	HistoryService_UpdateHistoryRead_FullMethodName = "/coins_service.HistoryService/UpdateHistoryRead"
)

// HistoryServiceClient is the client API for HistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryServiceClient interface {
	HistoryUser(ctx context.Context, in *HistoryUserRequest, opts ...grpc.CallOption) (*HistoryUserResponse, error)
	HistoryUserAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HistoryUserResponse, error)
	HistoryMessage(ctx context.Context, in *HistoryUserRequest, opts ...grpc.CallOption) (*HistoryMessageResponse, error)
	UpdateHistoryRead(ctx context.Context, in *HistoryUserRequest, opts ...grpc.CallOption) (*Empty, error)
}

type historyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryServiceClient(cc grpc.ClientConnInterface) HistoryServiceClient {
	return &historyServiceClient{cc}
}

func (c *historyServiceClient) HistoryUser(ctx context.Context, in *HistoryUserRequest, opts ...grpc.CallOption) (*HistoryUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryUserResponse)
	err := c.cc.Invoke(ctx, HistoryService_HistoryUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) HistoryUserAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HistoryUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryUserResponse)
	err := c.cc.Invoke(ctx, HistoryService_HistoryUserAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) HistoryMessage(ctx context.Context, in *HistoryUserRequest, opts ...grpc.CallOption) (*HistoryMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryMessageResponse)
	err := c.cc.Invoke(ctx, HistoryService_HistoryMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) UpdateHistoryRead(ctx context.Context, in *HistoryUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HistoryService_UpdateHistoryRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServiceServer is the server API for HistoryService service.
// All implementations must embed UnimplementedHistoryServiceServer
// for forward compatibility.
type HistoryServiceServer interface {
	HistoryUser(context.Context, *HistoryUserRequest) (*HistoryUserResponse, error)
	HistoryUserAll(context.Context, *Empty) (*HistoryUserResponse, error)
	HistoryMessage(context.Context, *HistoryUserRequest) (*HistoryMessageResponse, error)
	UpdateHistoryRead(context.Context, *HistoryUserRequest) (*Empty, error)
	mustEmbedUnimplementedHistoryServiceServer()
}

// UnimplementedHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryServiceServer struct{}

func (UnimplementedHistoryServiceServer) HistoryUser(context.Context, *HistoryUserRequest) (*HistoryUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryUser not implemented")
}
func (UnimplementedHistoryServiceServer) HistoryUserAll(context.Context, *Empty) (*HistoryUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryUserAll not implemented")
}
func (UnimplementedHistoryServiceServer) HistoryMessage(context.Context, *HistoryUserRequest) (*HistoryMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryMessage not implemented")
}
func (UnimplementedHistoryServiceServer) UpdateHistoryRead(context.Context, *HistoryUserRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHistoryRead not implemented")
}
func (UnimplementedHistoryServiceServer) mustEmbedUnimplementedHistoryServiceServer() {}
func (UnimplementedHistoryServiceServer) testEmbeddedByValue()                        {}

// UnsafeHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServiceServer will
// result in compilation errors.
type UnsafeHistoryServiceServer interface {
	mustEmbedUnimplementedHistoryServiceServer()
}

func RegisterHistoryServiceServer(s grpc.ServiceRegistrar, srv HistoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryService_ServiceDesc, srv)
}

func _HistoryService_HistoryUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).HistoryUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_HistoryUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).HistoryUser(ctx, req.(*HistoryUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_HistoryUserAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).HistoryUserAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_HistoryUserAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).HistoryUserAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_HistoryMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).HistoryMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_HistoryMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).HistoryMessage(ctx, req.(*HistoryUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_UpdateHistoryRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).UpdateHistoryRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_UpdateHistoryRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).UpdateHistoryRead(ctx, req.(*HistoryUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoryService_ServiceDesc is the grpc.ServiceDesc for HistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coins_service.HistoryService",
	HandlerType: (*HistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HistoryUser",
			Handler:    _HistoryService_HistoryUser_Handler,
		},
		{
			MethodName: "HistoryUserAll",
			Handler:    _HistoryService_HistoryUserAll_Handler,
		},
		{
			MethodName: "HistoryMessage",
			Handler:    _HistoryService_HistoryMessage_Handler,
		},
		{
			MethodName: "UpdateHistoryRead",
			Handler:    _HistoryService_UpdateHistoryRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history.proto",
}
